# This is a basic workflow to help you get started with Actions

name: CHECK_START

on:
  workflow_run:
    workflows: [CI_DEV]
    types:
      - requested


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: action-slack
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
              text: "deploy start!",
              attachments: [{
                "author_name": "check_start",
                fallback: 'fallback',
                color: 'good',
                title: 'CI Result',
                text: 'Successed',
                fields: [{
                  title: 'Error Msg',
                  value: 'null',
                  short: true
                }],
                actions: [{
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()
